//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentDeliverySystem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDSEntities : DbContext
    {
        public CDSEntities()
            : base("name=CDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contents> Contents { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Tokens> Tokens { get; set; }
        public virtual DbSet<TokenTypes> TokenTypes { get; set; }
        public virtual DbSet<UserTypes> UserTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ContentTypes> ContentTypes { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<GroupContents> GroupContents { get; set; }
    }
}
