//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentDeliverySystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        public Contents()
        {
            this.Tokens = new HashSet<Tokens>();
            this.Genres = new HashSet<Genres>();
            this.GroupContents = new HashSet<GroupContents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public bool IsBroadcast { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime BeginDeliveryDate { get; set; }
        public System.DateTime EndDeliveryDate { get; set; }
        public string ISBN { get; set; }
        public double Price { get; set; }
        public double Duration { get; set; }
        public int PublishYear { get; set; }
        public int IdType { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<Tokens> Tokens { get; set; }
        public virtual ContentTypes ContentTypes { get; set; }
        public virtual ICollection<Genres> Genres { get; set; }
        public virtual ICollection<GroupContents> GroupContents { get; set; }
    }
}
