//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentDeliverySystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genres
    {
        public Genres()
        {
            this.Children = new HashSet<Genres>();
            this.Contents = new HashSet<Contents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdParent { get; set; }
    
        public virtual ICollection<Genres> Children { get; set; }
        public virtual Genres Parent { get; set; }
        public virtual ICollection<Contents> Contents { get; set; }
    }
}
