//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentDeliverySystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Tokens = new HashSet<Tokens>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> IdType { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public string CPF { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string Phone { get; set; }
        public string Cellphone { get; set; }
        public string Adress { get; set; }
        public string CEP { get; set; }
        public string State { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual ICollection<Tokens> Tokens { get; set; }
        public virtual UserTypes UserTypes { get; set; }
    }
}
